server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

spring:
  config:
    name: ${APP_NAME:"dainf-lab-server"}
  application:
    name: ${APP_NAME:"dainf-lab-server"}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      org.hibernate.envers.store_data_at_delete: true
      org.hibernate.envers.global_with_modified_flag: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:andreytondo0408@gmail.com}
    password: ${MAIL_PASSWORD:jpyu vzvi fbin utbv}
    test-connection: false
    properties:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: java.net.ssl.SSLSocketFactory

jwt:
  secret: ${TOKEN_SECRET:VGt0MGNRU3p3VQ==}
  expiration: ${TOKEN_EXPIRATION:3600000} # 1 hora em ms
  refresh:
    expiration: ${TOKEN_REFRESH_EXPIRATION:2629746000} # 1 mes em ms
    secret: ${TOKEN_REFRESH_SECRET:Tkt0cQSzwU}

storage:
  url: ${MINIO_URL:http://localhost:9000}
  bucket: ${MINIO_BUCKET:dainf-lab}
  port: ${MINIO_PORT:9000}
  secure: ${MINIO_SECURE:false}
  access:
    key: ${MINIO_ACCESS_KEY:admin}
    secret: ${MINIO_SECRET_KEY:minio123}

